// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCRimk7K6Pgof2apDwuG8QEGqYpimkT4',
    appId: '1:717409004128:web:73e100f053b3f56d51f105',
    messagingSenderId: '717409004128',
    projectId: 'plant-viwe',
    authDomain: 'plant-viwe.firebaseapp.com',
    storageBucket: 'plant-viwe.firebasestorage.app',
    measurementId: 'G-VHTMLTJC2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2MFWT6equSRt_58qz1ppzm1h5Qf7l5JM',
    appId: '1:717409004128:android:f4c691a868ec1b9351f105',
    messagingSenderId: '717409004128',
    projectId: 'plant-viwe',
    storageBucket: 'plant-viwe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5aEEOElT3wvZQ8jFOMucUXaBTZalGj7g',
    appId: '1:717409004128:ios:f54eda6660ad3b9851f105',
    messagingSenderId: '717409004128',
    projectId: 'plant-viwe',
    storageBucket: 'plant-viwe.firebasestorage.app',
    iosClientId: '717409004128-qahjjknj9pi1odae3uhogligbbbtr3pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5aEEOElT3wvZQ8jFOMucUXaBTZalGj7g',
    appId: '1:717409004128:ios:f54eda6660ad3b9851f105',
    messagingSenderId: '717409004128',
    projectId: 'plant-viwe',
    storageBucket: 'plant-viwe.firebasestorage.app',
    iosClientId: '717409004128-qahjjknj9pi1odae3uhogligbbbtr3pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLCRimk7K6Pgof2apDwuG8QEGqYpimkT4',
    appId: '1:717409004128:web:b56b81c012f8f72751f105',
    messagingSenderId: '717409004128',
    projectId: 'plant-viwe',
    authDomain: 'plant-viwe.firebaseapp.com',
    storageBucket: 'plant-viwe.firebasestorage.app',
    measurementId: 'G-147TX63LJP',
  );
}
